### ISSUE TITLE
Draft Query Requirements

### ISSUE THREAD

**Issue by Psyf** [cs2102team60petcare/server#8]
Please let me know of the queries you need for each page of the website. 
This should be done along with #7.

**Comment by singjielim** [comment]
These are the queries we need for each page of the website!

**Sign Up**
(from users)
-name
-email
-password
if choose owner ref to owners
if choose caretaker ref to caretaker
-likes 

**Log In**
(from users)
-email
-password

**Contact**
(from users)
-userid
-name
-email
(from requests)
-message

**Search**
(from users)
-address
(from services)
-starting
-ending
(from caretakers)
-likes

**Comment by Psyf** [comment]
Query requirements clearer after UI/UX Meeting last night. 
Closing issue since not needed anymore. I will take over.
